import React,{useState} from "react";
import { useForm } from "react-hook-form";
import WYSIWYG from "./WYSIWYG";
import { IonInput, IonItem, IonLabel,IonButton} from '@ionic/react';
import Dropdown from "./Dropdown";
function Form(props) {
  let { register, handleSubmit } = useForm();
  let { form, setForm } = useState([]);
  let { id, name, properties } = props.template;
  const renderedData = properties.map(field => {
    let c =[{id:1,name:"test1"},{id:2,name:"test2"},{id:3,name:"test3"}] //test data
    let { name, property, propertyType, mandatory, validation, view, error, defaultValue, placeholder, autogenerated, combined, fields } = field;
    if(!autogenerated)
    {
      switch (view) {
        case "wysiwyg":
          return (<WYSIWYG title="Question" name={property} key={property}></WYSIWYG>);
        case "text":
          return (
            <IonItem key={property}>
              <IonLabel position="floating">{name}</IonLabel>
              <IonInput name={property} ></IonInput>
            </IonItem>
          );
        case "dropdown":
          return (
            <Dropdown name={property} title="Subject" key={property} choices={c}  />
            )
      }
    }
  });  
  return (
    <>
      <form onSubmit={handleSubmit(onSubmit)}>
        {renderedData}
        <IonButton mode ="md" expand="block" type="submit">Post Question</IonButton>
      </form>
    </>
  )
}
function onSubmit(values) {
  console.log("Submit is working");
}
export default Form;