import Form from "./Form";
import React from "react";
function ForumForm() {
  let template = {
    "id": "forum",
    "name": "Forum Table",
    "properties": [
      {
        "name": "ID",
        "property": "_id",
        "propertyType": "text",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "ID already exists",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": false,
        "fields": ""
      },
      {
        "name": "Date",
        "property": "date",
        "propertyType": "date",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "Invalid date",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": false,
        "fields": ""
      },
      {
        "name": "Title",
        "property": "title",
        "propertyType": "test",
        "mandatory": true,
        "validation": "",
        "view": "text",
        "error": "Question cant be empty",
        "defaultValue": "",
        "placeholder": "Enter Question Title",
        "autogenerated": "",
        "combined": "",
        "fields": ""
      },
      {
        "name": "User Information",
        "property": "userInfo",
        "propertyType": "text",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "Invalid User Information",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": true,
        "fields": ["user._id", "user.name", "user.type"]
      },
      {
        "name": "Subject",
        "property": "tagInfo",
        "propertyType": "text",
        "mandatory": true,
        "validation": "",
        "view": "dropdown",
        "error": "",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": false,
        "combined": true,
        "fields": ["tag._id", "tag.name"]
      },
      {
        "name": "Room Information",
        "property": "roomInfo",
        "propertyType": "text",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "Invalid Room ID",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": true,
        "fields": ["room._id", "room.name"]
      },
      {
        "name": "Content",
        "property": "content",
        "propertyType": "wysiwyg",
        "mandatory": true,
        "validation": "",
        "view": "wysiwyg",
        "error": "Answer cant be empty",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": false,
        "combined": false,
        "fields": ""
      },
      {
        "name": "Type of Data (Question/Answer)",
        "property": "typeForum",
        "propertyType": "bool",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "Invalid Type",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": false,
        "fields": ""
      },
      {
        "name": "Question ID",
        "property": "questionID",
        "propertyType": "text",
        "mandatory": true,
        "validation": "",
        "view": false,
        "error": "",
        "defaultValue": "",
        "placeholder": "",
        "autogenerated": true,
        "combined": false,
        "fields": ""
      }
        
    ]
  };

  return (<Form template={template}/>);
}
export default ForumForm;